INFO   |testbench|2018-03-26 01:53:48,954: starting experiment experiments.mnistnet...
ERROR  |testbench|2018-03-26 01:55:39,841: Oops! something went wrong: 'Logger' object has no attribute 'INFO'
ERROR  |testbench|2018-03-26 01:55:58,617: Oops! something went wrong: 
'Logger' object has no attribute 'INFO'
INFO   |testbench|2018-03-26 01:56:41,734: starting experiment experiments.mnistnet...
INFO   |testbench|2018-03-26 01:59:41,124: Starting experiment experiments.mnistnet...
ERROR  |testbench|2018-03-26 01:59:41,125: Oops! something went wrong: tuple index out of range
INFO   |testbench|2018-03-26 01:59:57,256: Starting experiment experiments.mnistnet...
INFO   |testbench|2018-03-26 01:59:57,256: Experiment iteration info: [{'batch': 50, 'epochs': range(1, 11)}, {'batch': 100, 'epochs': 2}, {'batch': 100, 'epochs': 3}]
INFO   |testbench|2018-03-26 02:00:17,009: Starting experiment experiments.mnistnet...
ERROR  |testbench|2018-03-26 02:00:17,010: Oops! something went wrong: module 'experiments.mnistnet' has no attribute 'iterations'
INFO   |testbench|2018-03-26 02:00:56,790: Starting experiment experiments.mnistnet...
ERROR  |testbench|2018-03-26 02:00:56,790: Oops! something went wrong: None module 'experiments.mnistnet' has no attribute 'iterations'
INFO   |testbench|2018-03-26 02:01:11,633: Starting experiment experiments.mnistnet...
ERROR  |testbench|2018-03-26 02:01:11,633: Oops! something went wrong: None: module 'experiments.mnistnet' has no attribute 'iterations'
INFO   |testbench|2018-03-26 02:01:30,204: Starting experiment experiments.mnistnet...
ERROR  |testbench|2018-03-26 02:01:30,205: Oops! something went wrong: <class 'AttributeError'>: module 'experiments.mnistnet' has no attribute 'iterations'
INFO   |testbench|2018-03-26 02:02:19,131: Starting experiment experiments.mnistnet...
INFO   |testbench|2018-03-26 02:02:19,131: Experiment iteration info: [[]]
INFO   |testbench|2018-03-26 02:03:51,704: Starting experiment experiments.mnistnet...
INFO   |testbench|2018-03-26 02:03:51,704: Experiment iteration info: [[]]
INFO   |testbench|2018-03-26 02:05:17,300: Starting experiment experiments.mnistnet...
INFO   |testbench|2018-03-26 02:05:17,300: Experiment iteration info: [{'batch': 50, 'epochs': range(1, 11)}, {'batch': 100, 'epochs': 2}, {'batch': 100, 'epochs': 3}]
ERROR  |testbench|2018-03-26 15:43:48,796: Oops! something went wrong: <class 'AttributeError'>: 'MNISTNET' object has no attribute '__name__'
INFO   |testbench|2018-03-26 15:44:11,200: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 15:44:11,201: Oops! something went wrong: <class 'NameError'>: name '_model_name_from_parameters' is not defined
INFO   |testbench|2018-03-26 15:45:42,950: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 15:45:42,950: Oops! something went wrong: <class 'TypeError'>: _model_name_from_parameters() missing 2 required positional arguments: 'batch_size' and 'epochs'
INFO   |testbench|2018-03-26 15:47:20,950: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 15:47:20,951: Oops! something went wrong: <class 'NotImplementedError'>: 
INFO   |testbench|2018-03-26 15:48:23,786: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 15:48:23,786: Oops! something went wrong: <class 'NotImplementedError'>:  
 <traceback object at 0x1c1ec16948>
INFO   |testbench|2018-03-26 15:48:51,892: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 15:48:51,892: Oops! something went wrong: <class 'NotImplementedError'>:  
 <traceback object at 0x1c2d9509c8>
INFO   |testbench|2018-03-26 15:51:22,255: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 15:51:22,255: Oops! something went wrong: <class 'NotImplementedError'>:  
 ['  File "testbench.py", line 74, in run\n    experiment.run(dataset, test_samples, 100, 1)\n', '  File "/Users/woods/Documents/Programming/greenmotherboard/experiments/experiment.py", line 297, in run\n    model_name = Experiment._model_name_from_parameters(batch_size, epochs, **kwargs)\n', '  File "/Users/woods/Documents/Programming/greenmotherboard/experiments/experiment.py", line 69, in _model_name_from_parameters\n    raise NotImplementedError\n']
INFO   |testbench|2018-03-26 15:52:11,486: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 15:52:11,486: Oops! something went wrong: <class 'NotImplementedError'>:  
 ['  File "testbench.py", line 74, in run\n    experiment.run(dataset, test_samples, 100, 1)\n', '  File "/Users/woods/Documents/Programming/greenmotherboard/experiments/experiment.py", line 297, in run\n    model_name = Experiment._model_name_from_parameters(batch_size, epochs, **kwargs)\n', '  File "/Users/woods/Documents/Programming/greenmotherboard/experiments/experiment.py", line 69, in _model_name_from_parameters\n    raise NotImplementedError\n']
INFO   |testbench|2018-03-26 15:57:05,483: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 15:57:05,484: Oops! something went wrong: <class 'NameError'>: name 'cls' is not defined 
 ['  File "testbench.py", line 74, in run\n    experiment.run(dataset, test_samples, 100, 1)\n', '  File "/Users/woods/Documents/Programming/greenmotherboard/experiments/experiment.py", line 297, in run\n    model_name = cls._model_name_from_parameters(batch_size, epochs, **kwargs)\n']
INFO   |testbench|2018-03-26 16:12:01,919: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 16:12:01,919: Oops! something went wrong: <class 'TypeError'>: _createmodel() missing 4 required positional arguments: 'X_test', 'y_test', 'batch_size', and 'epochs' 
 ['  File "testbench.py", line 74, in run\n    experiment.run(dataset, test_samples, 100, 1)\n', '  File "/Users/woods/Documents/Programming/greenmotherboard/experiments/experiment.py", line 312, in run\n    model = self.__internal_createmodel(dataset, batch_size, epochs, **kwargs)\n', '  File "/Users/woods/Documents/Programming/greenmotherboard/experiments/experiment.py", line 276, in __internal_createmodel\n    return self._createmodel(*dataset, **kwargs)\n']
INFO   |testbench|2018-03-26 16:12:48,971: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 16:12:48,971: Oops! something went wrong: <class 'TypeError'>: _createmodel() missing 2 required positional arguments: 'batch_size' and 'epochs' 
 ['  File "testbench.py", line 74, in run\n    experiment.run(dataset, test_samples, 100, 1)\n', '  File "/Users/woods/Documents/Programming/greenmotherboard/experiments/experiment.py", line 312, in run\n    model = self.__internal_createmodel(dataset, batch_size, epochs, **kwargs)\n', '  File "/Users/woods/Documents/Programming/greenmotherboard/experiments/experiment.py", line 276, in __internal_createmodel\n    return self._createmodel(*dataset, batch_size, epochs, **kwargs)\n']
INFO   |testbench|2018-03-26 16:16:54,203: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 16:16:58,682: Oops! something went wrong: <class 'TypeError'>: _fitmodel() argument after * must be an iterable, not int 
 ['  File "testbench.py", line 112, in run\n    experiment.run(dataset, test_samples, 100, 1)\n', '  File "/Users/woods/Documents/Programming/greenmotherboard/experiments/experiment.py", line 315, in run\n    self.__internal_fitmodel(dataset, batch_size, epochs, model, **kwargs)\n', '  File "/Users/woods/Documents/Programming/greenmotherboard/experiments/experiment.py", line 284, in __internal_fitmodel\n    return self._fitmodel(model, *dataset, batch_size, epochs, **kwargs)\n']
INFO   |testbench|2018-03-26 16:19:07,912: Starting experiment SIMPLE MNISTNET...
INFO   |testbench|2018-03-26 16:43:09,930: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 16:44:17,092: Oops! something went wrong: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: './experiments/models/SIMPLE MNISTNET/simple_mnistnet-b100-e.json' 
 ['  File "testbench.py", line 112, in run\n    experiment.run(dataset, test_samples, 100, 1)\n', '  File "C:\\Users\\Woods\\Desktop\\Programming\\greenmotherboard\\experiments\\experiment.py", line 318, in run\n    self.savemodel(model, model_name, **kwargs)\n', '  File "C:\\Users\\Woods\\Desktop\\Programming\\greenmotherboard\\experiments\\experiment.py", line 171, in savemodel\n    with open(directory + name+\'.json\', \'w\') as json_file:\n']
INFO   |testbench|2018-03-26 16:55:48,058: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 16:56:52,853: Oops! something went wrong: <class 'TypeError'>: evaluate() missing 1 required positional argument: 'kwargs' 
 ['  File "testbench.py", line 112, in run\n    experiment.run(dataset, test_samples, 100, 1)\n', '  File "C:\\Users\\Woods\\Desktop\\Programming\\greenmotherboard\\experiments\\experiment.py", line 330, in run\n    classes_acc = self.evaluate(model, test_samples, *kwargs)\n']
INFO   |testbench|2018-03-26 17:14:18,527: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 17:15:23,431: Oops! something went wrong: <class 'TypeError'>: evaluate() missing 1 required positional argument: 'kwargs' 
 ['  File "testbench.py", line 112, in run\n    experiment.run(dataset, test_samples, 100, 1)\n', '  File "C:\\Users\\Woods\\Desktop\\Programming\\greenmotherboard\\experiments\\experiment.py", line 330, in run\n    classes_acc = self.evaluate(model, test_samples, **kwargs)\n']
INFO   |testbench|2018-03-26 17:19:20,791: Starting experiment SIMPLE MNISTNET...
INFO   |testbench|2018-03-26 17:26:55,901: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 17:28:02,389: Oops! something went wrong: <class 'AttributeError'>: type object 'MNISTNET' has no attribute 'general_logger' 
 ['  File "testbench.py", line 112, in run\n    experiment.run(dataset, test_samples, 100, 1)\n', '  File "C:\\Users\\Woods\\Desktop\\Programming\\greenmotherboard\\experiments\\experiment.py", line 330, in run\n    classes_acc = self.evaluate(model, test_samples, **kwargs)\n', '  File "C:\\Users\\Woods\\Desktop\\Programming\\greenmotherboard\\experiments\\mnistnet.py", line 79, in evaluate\n    MNISTNET.general_logger.info(\'{}/{} correct ({})\'.format(correct_count, test_data_count, correct_count/test_data_count))\n']
INFO   |testbench|2018-03-26 17:30:39,353: Starting experiment SIMPLE MNISTNET...
ERROR  |testbench|2018-03-26 17:31:48,660: Oops! something went wrong: <class 'NameError'>: name 'np' is not defined 
 ['  File "testbench.py", line 112, in run\n    experiment.run(dataset, test_samples, 100, 1)\n', '  File "C:\\Users\\Woods\\Desktop\\Programming\\greenmotherboard\\experiments\\experiment.py", line 334, in run\n    self._generate_bar_char_img(classes_acc, model_name)\n', '  File "C:\\Users\\Woods\\Desktop\\Programming\\greenmotherboard\\experiments\\experiment.py", line 254, in _generate_bar_char_img\n    X = np.arange(len(d))\n']
INFO   |testbench|2018-03-26 17:33:52,313: Starting experiment SIMPLE MNISTNET...
